better parsing of bad arguments

diff --git a/alias b/alias
--- a/alias
+++ b/alias
@@ -26,7 +26,7 @@ do
             break
             ;;
         --*)
-            echo "error: invalid argument: $1" >&2
+            echo "alias: invalid argument: $1" >&2
             exit 1
             ;;
         *)
diff --git a/format_page b/format_page
--- a/format_page
+++ b/format_page
@@ -90,7 +90,7 @@ do
             break
             ;;
         --*)
-            echo "error: invalid argument: $1" >&2
+            echo "format_page: invalid argument: $1" >&2
             exit 1
             ;;
     esac
diff --git a/status-diff b/status-diff
--- a/status-diff
+++ b/status-diff
@@ -25,7 +25,7 @@ do
 			break
 			;;
 		--*)
-            echo "error: invalid argument: $1" >&2
+            echo "status-diff: invalid argument: $1" >&2
             exit 1
 			;;
 	esac
