add bad-argument check to status-diff

diff --git a/status-diff b/status-diff
--- a/status-diff
+++ b/status-diff
@@ -24,6 +24,10 @@ do
 			shift
 			break
 			;;
+		--*)
+            echo "error: invalid argument: $1" >&2
+            exit 1
+			;;
 	esac
 done
 
